config/routes.rb
Wtgsite::Application.routes.draw do |map|
  
  resources :blog_categories

  resources :categories

  root :to => "frontpage#index"
	
	match "contact", :to => "contacts#new", :as => "contact"

	match "login", :to => "user_sessions#new", :as => "login"
	
	match "logout", :to => "user_sessions#destroy", :as => "logout"
	
	resources :contacts
	
	resources :blocks do
	  member do
	    get :move_block_higher
	    get :move_block_lower
	  end
	end
	
	resources :columns do
	  resources :blocks
	  
	  member do
	    get :move_column_higher
	    get :move_column_lower
	  end
	end

  resources :blog_posts do
    resources :blog_comments, :member => { :moderate => :get }
  end
  
  resources :blog_comments, :member => { :moderate => :get }

  resources :user_sessions

  resources :users

  resources :pages do
    resources :columns
  end

	match 'frontpage' => 'frontpage#index'
	
	resources :blog, :controller => 'blog_posts'

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  self.per_page = 1
  has_friendly_id :title, :use_slug => true
  belongs_to :blog_category
	has_many :blog_comments
	belongs_to :user
	validates :title, :presence => true
	validates :body, :presence => true
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  respond_to :html, :xml, :json	
  before_filter :require_admin, :only => [:new, :edit, :create, :update, :destroy] 
    
  # GET /blog_posts
  # GET /blog_posts.xml
  def index
    #@blog_posts = BlogPost.all
    @blog_posts = BlogPost.paginate :page => params[:page], :order => 'updated_at DESC'
    @blog_categories = BlogCategory.all
    respond_with(@blog_posts)
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.xml
  def show
    @blog_post = BlogPost.find(params[:id])
    @approved_comments = @blog_post.blog_comments.where(:moderated => 1)
    @unapproved_comments = @blog_post.blog_comments.where(:moderated => 0)
    @new_blog_comment = @blog_post.blog_comments.new
    respond_with(@blog_post)
  end

  # GET /blog_posts/new
  # GET /blog_posts/new.xml
  def new
    @blog_post = BlogPost.new
    respond_with(@blog_post)
  end

  # GET /blog_posts/1/edit
  def edit
    @blog_post = BlogPost.find(params[:id])
  end

  # POST /blog_posts
  # POST /blog_posts.xml
  def create
    @blog_post = BlogPost.new(params[:blog_post])
		@blog_post.user_id = current_user.id #set author of blog post correctly
    flash[:notice] = "Blog Post successfully created" if @blog_post.save
    respond_with(@blog_post)
  end

  # PUT /blog_posts/1
  # PUT /blog_posts/1.xml
  def update
    @blog_post = BlogPost.find(params[:id])
    @blog_post.update_attributes(params[:blog_post])
    respond_with(@blog_post)
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.xml
  def destroy
    @blog_post = BlogPost.find(params[:id]).destroy
    respond_with(@blog_post)
  end
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper

  def snippet(blog_post)
  	#truncate blog post with ellipsis at 50 full words
    wordcount = 50  
    blog_post.split[0..(wordcount-1)].join(" ") + (blog_post.split.size > wordcount ? "..." : "")
  end
  
  def truncated?(text)
  	#check if post has been truncated by looking for ellipsis
    if text[-3,3] == "..."
    	return true
    else
      return false
    end
  end
  
end

app/views/blog_posts/_blog_post.html.erb
<section>
	<hgroup>
		<h1><%= link_to blog_post.title, blog_post %></h1>
		<h2>By <%= link_to blog_post.user.name, blog_post.user %></h2>
		<h3><% link_to blog_post_path(blog_post, :anchor => "comments") do %><%= blog_post.blog_comments.where(:moderated => 1).count %> Comments<% end %></h3>
	</hgroup>
	<p>
		<% body = snippet(blog_post.body) %>
		<%=raw body %>
		<% if truncated?(body) %>&nbsp;<%= link_to('[Read More]', :action => 'show', :id => blog_post) %><% end %>
	</p>
</section>
<div style="clear:both;"></div>

app/views/blog_posts/_form.html.erb
<%= form_for(@blog_post) do |f| %>
  <%= f.error_messages %>
  
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :blog_category_id %><br />
  <%= f.select :blog_category_id, BlogCategory.all.collect {|c| [ c.name, c.id ] }  %>
  </div> 
  <div class="field">
    <%= f.label :body %><br />
    <%= ckeditor_textarea("blog_post", "body", :width => '50%', :height => '200px') %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Editing blog_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_post %> |
<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/index.html.erb
<% if flash[:notice] %><p id="notice"><%= notice %></p><% end %>

<hgroup>
	<h1>Blog</h1>
	<% if current_user && current_user.is_admin? %>
	<h2><%= link_to "New Post", new_blog_post_path %> | <%= link_to "New Blog Category", new_blog_category_path %></h2>
	<% end %>
</hgroup>
<h2>Categories</h2>
<ul>
	<% @blog_categories.each do |blog_cat| %>
	<li><%= link_to blog_cat.name, blog_cat %><% if current_user && current_user.is_admin? %> (<%= link_to "Edit", edit_blog_category_path(blog_cat) %>, <%= link_to "Delete", blog_cat, :confirm => 'Are you sure you want to delete this blog category?', :method => :delete %>)<% end %></li>
	<% end %>
</ul>
<h2>Fresh Post</h2>
<%= render @blog_posts %>
<div style="clear:both;"></div>
<%= will_paginate @blog_posts %>

<%= render :partial => "layouts/blog_sidebar" %>

app/views/blog_posts/new.html.erb
<h1>New blog_post</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/show.html.erb
<% if flash[:notice] %><p id="notice"><%= notice %></p><% end %>

<hgroup>
	<h1><%= link_to "Blog", blog_posts_path %> > <%= link_to @blog_post.blog_category.name, @blog_post.blog_category %> > <%= @blog_post.title %></h1>
	<h2>By <%= link_to @blog_post.user.name, @blog_post.user %></h2>
	<h3><% link_to "#comments" do %><%= @blog_post.blog_comments.where(:moderated => 1).count %> Comments<% end %></h3>
	<% if current_user && current_user.is_admin? %>
	<h2><%= link_to 'Edit', edit_blog_post_path(@blog_post) %></h2>
	<% end %>
</hgroup>
  
<p><%=raw @blog_post.body %></p>

<h2 id="comments">Comments:</h2>

<% if current_user && current_user.is_admin? %>
	<% if @unapproved_comments.count == 1 %>
	<p>There is currently 1 unapproved comment for this post. <%= link_to "Manage it.", blog_post_blog_comments_path(@blog_post) %></p>
	<% elsif @unapproved_comments.count > 1 %>
	<p>There are currently <%= @unapproved_comments.count %> unapproved comments for this post. <%= link_to "Manage them.", blog_post_blog_comments_path(@blog_post) %></p>
	<% end %>
<% end %>

<% @approved_comments.each do |comment| %>
  By <%= comment.name %> (<%= comment.email %>) on <%= comment.created_at.strftime('%m/%d/%Y') %> 
    <% if comment.website != nil %>from <%= link_to comment.website, comment.website %><% end %>
  <p><%= comment.body %></p>
  <p>Admin Status: <%= comment.posted_by_admin? %></p>
<% end %>

<% if current_user && current_user.is_admin? %>
	<% admin_value = current_user.is_admin %>
<% else %>
	<% admin_value = 0 %>
<% end %>

<%= render :partial => "blog_comments/new", :locals => { :post => @blog_post, :comment => @new_blog_comment, :posted_by_admin => admin_value } %>