config/routes.rb
Wtgsite::Application.routes.draw do |map|
  
  resources :blog_categories

  resources :categories

  root :to => "frontpage#index"
	
	match "contact", :to => "contacts#new", :as => "contact"

	match "login", :to => "user_sessions#new", :as => "login"
	
	match "logout", :to => "user_sessions#destroy", :as => "logout"
	
	resources :contacts
	
	resources :blocks do
	  member do
	    get :move_block_higher
	    get :move_block_lower
	  end
	end
	
	resources :columns do
	  resources :blocks
	  
	  member do
	    get :move_column_higher
	    get :move_column_lower
	  end
	end

  resources :blog_posts do
    resources :blog_comments, :member => { :moderate => :get }
  end
  
  resources :blog_comments, :member => { :moderate => :get }

  resources :user_sessions

  resources :users

  resources :pages do
    resources :columns
  end

	match 'frontpage' => 'frontpage#index'
	
	resources :blog, :controller => 'blog_posts'

end

app/models/column.rb
class Column < ActiveRecord::Base
  acts_as_list :scope => :page
  belongs_to :page
  has_many :blocks, :order => "position"
end

app/controllers/columns_controller.rb
class ColumnsController < ApplicationController
  respond_to :html, :xml, :json
  before_filter :require_admin, :only => [:sort, :new, :edit, :create, :update, :destroy, :move_column_higher, :move_column_lower]     
  
  # GET /columns
  # GET /columns.xml
  def index
    @columns = Column.all
    respond_with(@columns)
  end

  # GET /columns/1
  # GET /columns/1.xml
  def show
    @column = Column.find(params[:id])
    respond_with(@column)
  end

  # GET /columns/new
  # GET /columns/new.xml
  def new
    @page = Page.find(params[:page_id]) 
    @column = @page.columns.new
    respond_with(@column)
  end

  # GET /columns/1/edit
  def edit
    @column = Column.find(params[:id])
  end

  # POST /columns
  # POST /columns.xml
  def create
    @page = Page.find(params[:page_id])
    @column = @page.columns.new(params[:column])
    flash[:notice] = "Column successfully created" if @column.save
    respond_with(@page)
  end

  # PUT /columns/1
  # PUT /columns/1.xml
  def update
    @column = Column.find(params[:id])
    @column.update_attributes(params[:column])
    respond_with(@column)
  end

  # DELETE /columns/1
  # DELETE /columns/1.xml
  def destroy
    @column = Column.find(params[:id])
    @page = @column.page
    @column.destroy
    respond_with(@page)
  end
  
  def move_column_higher
    @column = Column.find(params[:id])
    @page = @column.page
    flash[:notice] = "That column was moved up one space on the page." if @column.move_higher
    redirect_to(@page)
  end
  
  def move_column_lower
    @column = Column.find(params[:id])
    @page = @column.page
    flash[:notice] = "That column was moved down one space on the page." if @column.move_lower
    redirect_to(@page)
  end
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/views/columns/_column.html.erb
<section<% if current_user && current_user.is_admin? %> class="admin"<% end %> style="width:<%= column.width %>%;<% if column.is_clear? %>clear:both;<% end %>">
	<% if column.blocks.size == 0 %>
		<% if current_user && current_user.is_admin? %><%= link_to "Delete Empty Column", column, :confirm => 'Are you sure you want to delete this column?', :method => :delete %><% end %>
	<% else %>
		<%= render column.blocks %>
	<% end %>
	<br />
	<% if current_user && current_user.is_admin? %>(<%= link_to "Up", move_column_higher_column_path(column) %>, <%= link_to "Down", move_column_lower_column_path(column) %>, <%= link_to "Add Block Here", new_column_block_path(column) %><% end %>
</section>

app/views/columns/_form.html.erb
<% form_for([@page, @column]) do |f| %>
  <%= f.error_messages %>

  <div class="field">
    <%= f.label :width %><br />
    <%= f.text_field :width %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :is_clear %><br />
    <%= f.check_box :is_clear %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/columns/edit.html.erb
<h1>Editing column</h1>

<%= render 'form' %>

<%= link_to 'Show', @column %> |
<%= link_to 'Back', columns_path %>

app/views/columns/index.html.erb
<hgroup>
	<h1>Columns List</h1>
	<% if current_user && current_user.is_admin? %>
	<h2><%= link_to "Create New Column", new_column_path %></h2>
	<% end %>
</hgroup>
<ul>
	<% @columns.each do |column| %>
	<li>Column <%= column.id %> <% if current_user && current_user.is_admin? %>(<%= link_to "Edit", edit_column_path(column) %>, <%= link_to "Delete", column, :confirm => 'Are you sure you want to delete this column?', :method => :delete %>)<% end %></li>
	<% end %>
</ul>

app/views/columns/new.html.erb
<h1>New column for page <%= @page.title %></h1>

<%= render :partial => 'form', :locals => { :page => @page, :column => @column } %>

<%= link_to 'Back', columns_path %>