config/routes.rb
Wtgsite::Application.routes.draw do |map|
  
  resources :blog_categories

  resources :categories

  root :to => "frontpage#index"
	
	match "contact", :to => "contacts#new", :as => "contact"

	match "login", :to => "user_sessions#new", :as => "login"
	
	match "logout", :to => "user_sessions#destroy", :as => "logout"
	
	resources :contacts
	
	resources :blocks do
	  member do
	    get :move_block_higher
	    get :move_block_lower
	  end
	end
	
	resources :columns do
	  resources :blocks
	  
	  member do
	    get :move_column_higher
	    get :move_column_lower
	  end
	end

  resources :blog_posts do
    resources :blog_comments, :member => { :moderate => :get }
  end
  
  resources :blog_comments, :member => { :moderate => :get }

  resources :user_sessions

  resources :users

  resources :pages do
    resources :columns
  end

	match 'frontpage' => 'frontpage#index'
	
	resources :blog, :controller => 'blog_posts'

end

app/models/block.rb
class Block < ActiveRecord::Base
  acts_as_list :scope => :column
  belongs_to :column
end

app/models/blog_category.rb
class BlogCategory < ActiveRecord::Base
	has_many :blog_posts
	validates :name, :presence => true
end

app/models/blog_comment.rb
class BlogComment < ActiveRecord::Base
	belongs_to :blog_post
	validates :body, :presence => true
	validates :name, :presence => true
	validates :email, :presence => true
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  self.per_page = 1
  has_friendly_id :title, :use_slug => true
  belongs_to :blog_category
	has_many :blog_comments
	belongs_to :user
	validates :title, :presence => true
	validates :body, :presence => true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :pages
end

app/models/column.rb
class Column < ActiveRecord::Base
  acts_as_list :scope => :page
  belongs_to :page
  has_many :blocks, :order => "position"
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/page.rb
class Page < ActiveRecord::Base
  has_friendly_id :title, :use_slug => true
  belongs_to :category
  has_many :columns, :order => "position"
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/models/user.rb
class User < ActiveRecord::Base
	acts_as_authentic
	has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	has_many :blog_posts
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  respond_to :html, :xml, :json
  before_filter :require_admin, :only => [:new, :edit, :create, :update, :destroy]   
    
  # GET /pages
  # GET /pages.xml
  def index
    @pages = Page.all
    respond_with(@pages)
  end

  # GET /pages/1
  # GET /pages/1.xml
  def show
    @page = Page.find(params[:id])
    @columns = @page.columns.order("position ASC")
    respond_with(@page)
  end

  # GET /pages/new
  # GET /pages/new.xml
  def new
    @page = Page.new
    respond_with(@page)
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find(params[:id])
  end

  # POST /pages
  # POST /pages.xml
  def create
    @page = Page.new(params[:page])
    flash[:notice] = "Page successfully created" if @page.save
    respond_with(@page)
  end

  # PUT /pages/1
  # PUT /pages/1.xml
  def update
    @page = Page.find(params[:id])
    @page.update_attributes(params[:page])
    respond_with(@page)
  end

  # DELETE /pages/1
  # DELETE /pages/1.xml
  def destroy
    @page = Page.find(params[:id])
    @page.destroy
    respond_with(@page)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html, :xml, :json
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => [:show, :edit, :update, :destroy] 
  before_filter :require_admin, :only => [:index]
  
  # GET /users
  # GET /users.xml
  def index
		@users = User.order('name ASC').all
    respond_with(@users)
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    if params[:id] != current_user.id && current_user.is_admin == false
    	raise "You are not authorized to access this function"
    end
    @user = User.find(params[:id])
    respond_with(@user)
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new
    respond_with(@user)
  end

  # GET /users/1/edit
  def edit
    if params[:id] != current_user.id && current_user.is_admin == false
    	raise "You are not authorized to access this function"
    end  
    @user = current_user
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])
    flash[:notice] = "User successfully created" if @user.save
    respond_with(@user)
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    if params[:id] != current_user.id && current_user.is_admin == false
    	raise "You are not authorized to access this function"
    end  
    @user = current_user
    @user.update_attributes(params[:user])
    respond_with(@user)
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    if params[:id] != current_user.id && current_user.is_admin == false
    	raise "You are not authorized to access this function"
    end  
    @user = User.find(params[:id]).destroy
    respond_with(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper

  def snippet(blog_post)
  	#truncate blog post with ellipsis at 50 full words
    wordcount = 50  
    blog_post.split[0..(wordcount-1)].join(" ") + (blog_post.split.size > wordcount ? "..." : "")
  end
  
  def truncated?(text)
  	#check if post has been truncated by looking for ellipsis
    if text[-3,3] == "..."
    	return true
    else
      return false
    end
  end
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_blog_sidebar.html.erb
<% # feel free to use this partial to include a sidebar for the blog with anything you'd like to add %>

<aside>
	
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= controller.controller_name.titleize %> - Our Website</title>
<%= stylesheet_link_tag    "application" %>
<%= javascript_include_tag "application" %>
	<%= javascript_include_tag :ckeditor %>
	<%= stylesheet_link_tag 'foundation' %>
	<%= csrf_meta_tag %>

	<!--[if lt IE 9]>
	<%= javascript_include_tag "html5.js" %>
	<![endif]-->
</head>
<body<% if controller.controller_name == "pages" && controller.action_name == "show" %> class="category_<%= @page.category.name.downcase %>"<% end %>>
	<header>
		<% if current_user %>
		<p>Logged in as <%= current_user.username %></p>
		<ul>
			<% if current_user.is_admin? %>
			<li><%= link_to "Manage Users", users_path %></li>
			<% end %>
			<li><%= link_to "Logout", logout_path %></li>
		</ul>
		<% else %>
		<ul>
			<li><%= link_to "Register", new_user_path %></li>
			<li><%= link_to "Login", login_path %></li>
		</ul>
		<% end %>
		<%= link_to image_tag("your_logo_here.png", :alt => "The Logo", :title => "Home"), frontpage_path %>
	</header>
	<% if flash[:notice] %>
	<p id="flashblock"><%= flash[:notice] %></p>
	<% end %>
	
	<% # if this is pages/show/:id and a partial exists for the category, load that; otherwise, yield normally: %>
	<% if controller.controller_name == "pages" && controller.action_name == "show" %>
    	<% if FileTest.exists?(RAILS_ROOT + '/app/views/category_includes/' + '_' + @page.category.name.downcase + '.html.erb') %>
		<%= render :partial => 'category_includes/' + @page.category.name.downcase %>
	  	<% else %>
		<article>
	  		<%= yield %>
  		</article>
		<% end %>
	<% else %>
  	<article>
	  	<%= yield %>
  	</article>
	<% end %>
	
	<footer>
	</footer>
</body>
</html>

app/views/layouts/basic.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>Our Website - <%= controller.controller_name.capitalize %></title>
   <%= stylesheet_link_tag "main", :media => "all" %>
   <%= javascript_include_tag :defaults %>
	 <%= javascript_include_tag :ckeditor %>
</head>
<body>
	 <%= render :partial => "includes/login" %>
   <div id="wrap"><div id="page">
      <div id="header">
         <div id="header-padding">
            <%= link_to image_tag("your_logo_here.png", :alt => "The Logo", :title => "Home") %>
         </div>
      </div>
      <div id="maincell">
         <% if flash[:notice] %><p id="flashblock"><%= flash[:notice] %></p><% end %>
         <%= yield %>
      </div>
      <div id="footer">
      	<% if !current_user %>
					<%= link_to "Register", new_user_path %>|
					<%= link_to "Login", login_path %>
				<% end %>
      </div>
   </div></div>

</body>
</html>